kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-object-privileged-scc
subjects:
  - kind: ServiceAccount
    name: object-sa
    namespace: object-detection
roleRef:
  kind: ClusterRole
  name: object-cluterrole
  apiGroup: rbac.authorization.k8s.io

